### ISSUE TITLE
Is there a version that supports .net 4.8?

### ISSUE THREAD

**Issue by huliganhak** [calico-crusade/palworld-rcon-sharp#1]
Is there a version that supports .net 4.8?

**Comment by calico-crusade** [comment]
It does now! I targeted .net standard 2.1 in version 1.0.2. I also updated the readme with examples of how to use it. 

However, I would suggest moving to newer version so .net as I'm pretty sure that .net framework is considered legacy technology and isn't getting the performance improvements that .net 5+ has seen.
